name: Generate Snake Game

on:
  schedule:
    - cron: "14 5 * * *"
  workflow_dispatch:

jobs:
  generate-snake-game:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake Game
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/github-snake.svg
            assets/github-snake-dark.svg?palette=github-dark

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v10
        with:
          message: "generate snake game 🐍"
          default_author: github_actions
